// <auto-generated />
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("TalegenProjectNamiCacheLoader")]
[assembly: AssemblyDescription("Talegen version of Project Nami Cache Loader Web Job")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Talegen, LLC")]
[assembly: AssemblyProduct("TalegenProjectNamiCacheLoader")]
[assembly: AssemblyCopyright("Copyright ©  2018 Talegen, LLC.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("82e787c6-cc48-49f6-9a98-8bf29614c7f7")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Revision and Build Numbers 
// by using the '*' as shown below:
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: NeutralResourcesLanguage("en")]
