//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalegenProjectNamiCacheLoader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TalegenProjectNamiCacheLoader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error -  An error occurred during the Get Request of [{0}]. 
        ///Exception Messages: 
        ///{1}
        ///Stack: 
        ///{2}.
        /// </summary>
        internal static string PageGetResponseExceptionErrorMessageText {
            get {
                return ResourceManager.GetString("PageGetResponseExceptionErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error -  An error occurred during the parsing of content in [{0}]. 
        ///Exception Messages: 
        ///{1}
        ///Stack: 
        ///{2}.
        /// </summary>
        internal static string PageParseExceptionErrorMessageText {
            get {
                return ResourceManager.GetString("PageParseExceptionErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning - Attempted to request [{0}] and returned status code {1} {2}..
        /// </summary>
        internal static string PageRequestErrorMessageText {
            get {
                return ResourceManager.GetString("PageRequestErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - An error occurred during the processing of [{0}]. Skipped.
        ///Exception Messages: 
        ///{1}
        ///Stack: 
        ///{2}.
        /// </summary>
        internal static string PageRequestExceptionErrorMessageText {
            get {
                return ResourceManager.GetString("PageRequestExceptionErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key....
        /// </summary>
        internal static string PressAnyKeyText {
            get {
                return ResourceManager.GetString("PressAnyKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} inner links found in [{1}]....
        /// </summary>
        internal static string ProcessingInnerLinksText {
            get {
                return ResourceManager.GetString("ProcessingInnerLinksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Site [{0}] Complete..
        /// </summary>
        internal static string ProcessingSiteEndText {
            get {
                return ResourceManager.GetString("ProcessingSiteEndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Site [{0}] Start....
        /// </summary>
        internal static string ProcessingSiteStartText {
            get {
                return ResourceManager.GetString("ProcessingSiteStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited - {0} in {1:0.###} second(s)..
        /// </summary>
        internal static string VisitedSiteResultMessageText {
            get {
                return ResourceManager.GetString("VisitedSiteResultMessageText", resourceCulture);
            }
        }
    }
}
